import type { Metadata } from "next";
import "./styles/globals.css";

export const metadata: Metadata = {
  title: "Base Assistant UI",
  description: "Downloadable assistant-ui demo starter generated by Xulux.",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>{children}</body>
    </html>
  );
}
