import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StdioClientTransport } from "@modelcontextprotocol/sdk/client/stdio.js";
const t = new StdioClientTransport({ command: process.execPath, args: ["/tmp/mcp-smoke-server.mjs"] });
const c = new Client({ name: "smoke-client", version: "1" });
await c.connect(t);
const tools = await c.listTools();
console.log("tools:", tools.tools.map((x) => x.name).join(","));
const r = await c.callTool({ name: "echo", arguments: { text: "ok" } });
const text = (r.content as Array<{ type: string; text?: string }>)?.[0]?.text;
console.log("call:", text);
await c.close();
console.log("SMOKE_OK");
